Revert "[Payables Agent] Enable historical line matching experiment (#5227)" (#5372)
This reverts commit e0e273b5d99ebe561c030da5c6d7533cf2dd363f.
as it break the CICD build:

> Compilation started for project 'E-Document Core' containing '294'
files at '11:52:20.590'.
Error: AS0074 Found Obsolete Tag with value '27.0' in the baseline and
value '28.0' in current branch for Enum 'EDoc Vendor Matching Scope'.
Obsolete Tag must be the same across branches.
Error: AS0074 Found Obsolete Tag with value '27.0' in the baseline and
value '28.0' in current branch for Table 'EDoc Historical Matching
Setup'. Obsolete Tag must be the same across branches.
Error: AS0074 Found Obsolete Tag with value '27.0' in the baseline and
value '28.0' in current branch for Enum 'EDoc Line Matching Scope'.
Obsolete Tag must be the same across branches.
  Compilation ended at '11:52:41.248'.


[AB#604259](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/604259)